name: Brandon Cardoso
url: http://bcardo.so

gems: [jekyll-paginate]
paginate: 10
paginate_path: "/posts/:num/"

category_dir: /category

markdown: kramdown
permalink: /post/:title
timezone: America/Toronto

defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: "post"
        values:
            layout: "post"
            customClass: "post"
            author: "Brandon Cardoso"
