name: Brandon Cardoso
url: www.bcardo.so
title: Brandon Cardoso
description: "A software developer from Toronto, Canada just trying to figure out what he wants."

gems: [jekyll-paginate]
paginate: 10
paginate_path: "/posts/:num/"

category_dir: /category

date_format: "%d %b %Y"

markdown: kramdown
permalink: /post/:title
timezone: America/Toronto

twitter_handle: "@bcardo_so"

defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: "post"
        values:
            layout: "post"
            customClass: "post"
            author: "Brandon Cardoso"
